### ISSUE TITLE
Add `psyplot`-related packages to the recipe

### ISSUE THREAD

**Issue by schlunma** [conda-forge/esmvaltool-suite-feedstock#6]
### Comment:

https://github.com/ESMValGroup/ESMValTool/pull/2653 added a couple of new dependencies that we need to add to the recipe for the next release:

```yaml
  - psy-maps
  - psy-reg
  - psy-simple
  - psyplot
```

**Comment by valeriupredoi** [comment]
great! I was 89% you forgot to open an issue about [Psy](https://www.youtube.com/watch?v=9bZkp7q19f0), was heading straight to New Issue :rofl:

**Comment by valeriupredoi** [comment]
@sloosvel pls bear this in mind when the bot PR comes along, hopefully later today :+1:

**Comment by sloosvel** [comment]
Adressed in #10
